### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by mhmtz** [Norgul/xmpp-php#14]
I get the following error while texting. Why?

Fatal error: Uncaught TypeError: Return value of Norgul\Xmpp\XmppClient::initDependencies() must be an instance of Norgul\Xmpp\void, none returned in /home/domain/public_html/src/XmppClient.php:51 Stack trace: #0 /home/domain/public_html/c2msj/src/XmppClient.php(43): Norgul\Xmpp\XmppClient->initDependencies() #1 /home/cplusxyz/public_html/index.php(19): Norgul\Xmpp\XmppClient->__construct(Object(Norgul\Xmpp\Options)) #2 /home/domain/public_html/index.php(114): Norgul\Xmpp\test('mhmtz', 'anon-a0ffd6926c...', '557b2a84cc1f64c...', 'hello') #3 {main} thrown in /home/domain/public_html/src/XmppClient.php on line 51

**Comment by Norgul** [comment]
Which version of PHP are you running?

**Comment by mhmtz** [comment]
Current PHP version: 7.3

**Comment by Norgul** [comment]
Do you have some domain disabled functions on your production? Something like [this](https://support.plesk.com/hc/en-us/articles/115000821654-Domain-s-PHP-functional-is-not-available-xxx-has-been-disabled-for-security-reasons)?

**Comment by mhmtz** [comment]
Thank you master, it work.
