### ISSUE TITLE
Wrong date format in logger

### ISSUE THREAD

**Issue by WelterRocks** [Norgul/xmpp-php#16]
The "minute" format in logger is incorrect. The logs show the time as HOUR:MONTH:SECOND not HOUR:MINUTE:SECOND ;-)

**Comment by Norgul** [comment]
@WelterRocks Funny how I never noticed it before :D Thanks. As with other issue, please feel free to submit any PR's, last few months I got other priorities so I don't have as much time to take care of this repo, but I'd like to improve it and reduce issues as much as possible

**Comment by WelterRocks** [comment]
Will send a pull request ;-)
