### ISSUE TITLE
Connect With Jabbim

### ISSUE THREAD

**Issue by jrpikong** [Norgul/xmpp-php#3]
Hi @Norgul I'm back, 
I use the last version . 
I can't connect with jabbim.com
![Screenshot from 2019-04-16 17-02-09](https://user-images.githubusercontent.com/2731812/56200772-a5bd7400-6069-11e9-828c-609906ee740a.png)
![Screenshot from 2019-04-16 17-01-51](https://user-images.githubusercontent.com/2731812/56200773-a6560a80-6069-11e9-8b07-78c2090d4f2e.png)

`
<?xml version="1.0" encoding="UTF-8"?>
<stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" id="16631993638058903553" version="1.0" xml:lang="en" from="jabbim.com">
   <stream:features>
      <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls">
         <required />
      </starttls>
   </stream:features>
   <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
      <encryption-required />
   </failure>
   <stream:error>
      <not-well-formed xmlns="urn:ietf:params:xml:ns:xmpp-streams" />
      <text xmlns="urn:ietf:params:xml:ns:xmpp-streams" xml:lang="en">not well-formed (invalid token)</text>
   </stream:error>
</stream:stream>
`
can you help me ?

**Comment by Norgul** [comment]
Sure, I will take a look and get back at you

**Comment by Norgul** [comment]
It looks like Jabbim uses TLS which I didn't yet implement in the library. I will do that and inform you once done

**Comment by Norgul** [comment]
Hello @jrpikong,
can you try out the new version `2.1.0`? 

Along with your options just add `->setTls(true);`

**Comment by Norgul** [comment]
@jrpikong I am closing the issue as the feature is implemented. Let me know if there is anything else needed. Thanks

**Comment by jrpikong** [comment]
Hi @Norgul I have new error if I try to use TLS 

`namespace Norgul\Xmpp;
class Example
{
    protected static $host     = 'jabbim.com';
    protected static $port     = 5222;
    protected static $username = 'deny123@jabbim.com';
    protected static $password = 'password213';
    public static function go()
    {
        $options = new Options();
        $options
            ->setHost(self::$host)
            ->setPort(self::$port)
            ->setUsername(self::$username)
            ->setPassword(self::$password)
            ->setUseTls(true);
        $client = new XmppClient($options);
        $client->connect();
        $client->iq->getRoster();
        $client->message->send('Hello world', 'smtel_001@jabbim.com');
        // Uncomment if you want to manually enter raw XML (or call a function) and see a server response
//        (new self)->sendRawXML($client);
        do {
            $response = $client->getResponse();
            $client->prettyPrint($response);
        } while (true);
        $client->disconnect();
    }
}`

and This the response : 

`
sniper@sniper:~/Projects/smtel/jabber$ php Example.php 
PHP Warning:  Module 'curl' already loaded in Unknown on line 0
PHP Warning:  fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown in /home/sniper/Projects/smtel/jabber/vendor/norgul/xmpp-php/src/Socket.php on line 53
`

**Comment by Norgul** [comment]
Hello @jrpikong, which version are you using?

**Comment by Norgul** [comment]
Response from server I'm getting is the following:

```
<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
    <not-authorized/>
    <text xml:lang='en'>Invalid username or password</text>
</failure>
```

Are you sure credentials are okay?

Btw, if you download the new version (`v2.1.5`) you can get rid of `setUseTls(true)` argument. TLS if supported is now enabled by default
